import type {
  AllTimeArtist,
  AllTimeFile,
  AllTimeSong,
  DataHealth,
  IndexSong,
  SongDetail,
  Summary,
  TopSong,
} from "./types";

// All data is static JSON generated by scripts/generate_frontend_data.py.
// BASE_URL makes this work under GitHub Pages sub-paths and Vercel root alike.
const DATA = `${import.meta.env.BASE_URL}data/`;

async function getJSON<T>(path: string): Promise<T> {
  const res = await fetch(`${DATA}${path}`, { cache: "no-cache" });
  if (!res.ok) throw new Error(`Failed to load ${path} (${res.status})`);
  return (await res.json()) as T;
}

export const fetchSummary = () => getJSON<Summary>("summary.json");
export const fetchTopSongs = () => getJSON<TopSong[]>("top_songs.json");
export const fetchSongIndex = () => getJSON<IndexSong[]>("song_index.json");
export const fetchDataHealth = () => getJSON<DataHealth>("data_health.json");
export const fetchSong = (id: string) =>
  getJSON<SongDetail>(`songs/${encodeURIComponent(id)}.json`);
export const fetchSongsAllTime = () =>
  getJSON<AllTimeFile<AllTimeSong>>("songs_alltime.json");
export const fetchArtistsAllTime = () =>
  getJSON<AllTimeFile<AllTimeArtist>>("artists_alltime.json");
